### ISSUE TITLE
Adjust OS:Nova:Server to changed security_groups requirements

### ISSUE THREAD

**Issue by felixfiskare** [evoila/heat-iaas#12]
Since Ocata Release [OS::Nova::Server](https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Nova::Server) has the following requirements for the optional property [security_groups](https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Nova::Server-prop-security_groups):

> #### security_groups
> List of security group names or IDs. Cannot be used if neutron ports are associated with this server; assign security groups to the ports instead.

At least the [basic instance](https://github.com/evoila/heat-iaas/blob/master/src/instance/basic.yaml) needs to be changed accordingly, other occurences of OS:Nova:Server should be checked as well

**Comment by ghost** [comment]
Correct, please submit a pull request

**Comment by felixfiskare** [comment]
Is OS::Nova::Server used in any other repo than heat-iaas?
